#!/usr/bin/python

import ConfigParser
import argparse
import subprocess


parser = argparse.ArgumentParser(
    description='Capture multiple webpages with one command'
)
parser.add_argument(
    '-e', '--environment',
    nargs=1,
    default=['live'],
    help='which prefix to use when grabbing'
)
parser.add_argument(
    'configuration_files',
    metavar='filename',
    nargs='+',
    help='INI-style configuration file'
)
args = parser.parse_args()

config = ConfigParser.SafeConfigParser()
config.read(args.configuration_files)

webkit2png = 'webkit2png'
if 'grabber' in config.sections():
    grabber = config.get('grabber', 'command')


for name in config.options('paths'):
    command = [ grabber ]

    if 'widths' in config.sections():
        for width in config.options('widths'):
            command.append( '-W%s' % config.get('widths', width) )

    command.append('-o')
    command.append(name)

    if 'grabber_options' in config.sections():
        for arg in config.options('grabber_options'):
            command.append(arg)
            if config.get('grabber_options', arg):
                command.append(config.get('grabber_options', arg))

    url = '%s%s' % (
            config.get('prefix', args.environment[0]),
            config.get('paths', name),
        )
    command.append(url)

    subprocess.call( command, shell=False )
